// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarEchart: typeof import('./src/components/echarts/bar-echart.vue')['default']
    BarEchart3d: typeof import('./src/components/echarts/bar-echart-3d.vue')['default']
    BaseFirstTitle: typeof import('./src/components/titleSection/base-first-title.vue')['default']
    BaseMiddleTitle: typeof import('./src/components/titleSection/base-middle-title.vue')['default']
    BaseModuleBg: typeof import('./src/components/otherSection/base-module-bg.vue')['default']
    BaseSecondTitle: typeof import('./src/components/titleSection/base-second-title.vue')['default']
    BaseSmallTitle: typeof import('./src/components/titleSection/base-small-title.vue')['default']
    BaseThirdTitle: typeof import('./src/components/titleSection/base-third-title.vue')['default']
    HeaderNav: typeof import('./src/components/headerNav.vue')['default']
    InfeedBarEchart: typeof import('./src/components/echarts/infeed-bar-echart.vue')['default']
    LineAreaChart: typeof import('./src/components/echarts/line-area-chart.vue')['default']
    LineAreaEchart: typeof import('./src/components/echarts/line-area-echart.vue')['default']
    LineChart: typeof import('./src/components/echarts/line-chart.vue')['default']
    LiquidfillEchart: typeof import('./src/components/echarts/liquidfillEchart.vue')['default']
    ModuleTitle: typeof import('./src/components/moduleTitle.vue')['default']
    NameNumber: typeof import('./src/components/other/name-number.vue')['default']
    PartPie: typeof import('./src/components/echarts/partPie.vue')['default']
    PieChart2d: typeof import('./src/components/echarts/pie-chart-2d.vue')['default']
    PieHchart1: typeof import('./src/components/highCharts3d/pieHchart1.vue')['default']
    PieHchart2: typeof import('./src/components/highCharts3d/pieHchart2.vue')['default']
    PieHchart3: typeof import('./src/components/highCharts3d/pieHchart3.vue')['default']
    Radar: typeof import('./src/components/echarts/radar.vue')['default']
    RadarEchart: typeof import('./src/components/echarts/radar-echart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollRanking: typeof import('./src/components/other/scroll-ranking.vue')['default']
    SectionShow: typeof import('./src/components/sectionShow.vue')['default']
    SingleNumber: typeof import('./src/components/other/single-number.vue')['default']
    SlideHeaderNav: typeof import('./src/components/slideHeaderNav.vue')['default']
    SwiperRanking: typeof import('./src/components/other/swiper-ranking.vue')['default']
    TabsButton: typeof import('./src/components/other/tabsButton.vue')['default']
    WordCloud: typeof import('./src/components/echarts/wordCloud.vue')['default']
  }
}
