/*
 * @Descripttion:
 * @Author: peiqf
 * @Date: 2025-04-23 15:04:37
 * @LastEditors: peiqf
 * @LastEditTime: 2025-04-23 16:16:36
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseBigPageHeadHyym: (typeof import('./src/components/common/base-big-page-head-hyym.vue'))['default']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
  }
}
